### ISSUE TITLE
feature request - copy to clipboard

### ISSUE THREAD

**Issue by RaphyRaph** [AntonioJMartinez/sketch-ImageAverageColor#2]
could you create a copy color HEX to clipboard command? importing colors to global palette is quite unwieldy

**Comment by AntonioJMartinez** [comment]
Sorry for the late reply @RaphyRaph. Well, actually both global and document palettes is the way you manage and save colors in Sketch. But I'll definitely implement it as soon as I get some free time if that's helpful.

**Comment by AntonioJMartinez** [comment]
Already pushed @RaphyRaph. Now you can update the plugin via both sketch toolbox and downloading it again manually. Hope this helps.
